# Generated by Django 4.0.5 on 2022-06-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contador_menasje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contador',
            old_name='menasje',
            new_name='mensaje',
        ),
    ]
